spawn:
  x: 0
  y: 100
  z: 0
  world: world
  enabled: true

use_real_world_names: false
multi_world_teleport: true

allowed_worlds:
  - world
  - world_nether
  - world_the_end

allowed_worlds_colors:
  - 'green'
  - 'gold'
  - 'light_purple'

custom_world_names:
  - Overworld
  - Nether
  - End
